spring:
  application:
    name: settlement-worker

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  datasource:
    url: jdbc:mysql://leopay-mysql.orb.local:3306/leopay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: leopay
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: settlement-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379
  batch:
    job:
      enabled: false  # 자동 실행 비활성화 (Week 4에서 스케줄 설정)
    jdbc:
      initialize-schema: always  # Batch 메타 테이블 자동 생성

settlement:
  batch:
    chunk-size: 100  # A-5: 10/50/100/500/1000으로 바꿔가며 성능 측정
